### PR TITLE
Updating to latest dojo/shim

### PR DESCRIPTION
**Pull request by rorticus**
**Description:**

Updating to use latest shim, https://github.com/dojo/shim/pull/101.

### CODE REVIEW

**Comment by rorticus** [comment]
ci failures are unrelated. tests in master are failing right now due to update in globalize/cldr

**Comment by agubler** [comment]
@rorticus should we pin the dependency?

**Comment by rorticus** [comment]
@mwistrand do you have thoughts on this?

**Comment by mwistrand** [comment]
I would be okay with pinning the version and manually updating as changes are verified to not break anything. In this case, the tests are failing because timezone offsets are now separated with U+2212 (minus sign). I've been trying to get a fix in but am currently fighting issues with npm/node.

**Comment by mwistrand** [comment]
I'll open an issue and corresponding PR.

**Pull request merged**
