### PR TITLE
Update `load()` usage.

### PR DESCRIPTION
**Pull request by lzhoucs**
**Type:** cleanup

**Description:** 

This cleans up boilerplate code that has been baked into `dojo-core/load`.

Note, The build/unit tests should fail until https://github.com/dojo/core/pull/262 is released.

Depends on: https://github.com/dojo/core/pull/262

**Related Issue:** N/A

### CODE REVIEW

**Comment by mwistrand** [comment]
Now that dojo/core#270 has landed, this PR can be updated to use the `useDefault` mapper, correct?

**Comment by lzhoucs** [comment]
I think so too, Matt! Will do it shortly!

**Comment by rorticus** [comment]
@mwistrand @lzhoucs I didn't realize this PR existed... 😄 I have https://github.com/dojo/i18n/pull/56 to update `load` to use the new request API from dojo/core. If you can use anything from there, great, otherwise just toss it.

**Comment by lzhoucs** [comment]
@rorticus thanks! This one is simply updating the `load` usage. It is not touching `request`.

**Comment by lzhoucs** [comment]
This one is very minor anyways. Maybe we can just close it and add those lines whenever we clean up the code in the future.

**Pull request closed without merging**
